# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/proto/streaming.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/proto/streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19src/proto/streaming.proto\x12\tstreaming\"\x1e\n\rStreamRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\"x\n\x0eStreamResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x17\n\x0fsequence_number\x18\x02 \x01(\x03\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12)\n\x06status\x18\x04 \x01(\x0e\x32\x19.streaming.ResponseStatus*-\n\x0eResponseStatus\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\x08\n\x04\x44ONE\x10\x02\x32W\n\x10StreamingService\x12\x43\n\nStreamData\x12\x18.streaming.StreamRequest\x1a\x19.streaming.StreamResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.proto.streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPONSESTATUS']._serialized_start=194
  _globals['_RESPONSESTATUS']._serialized_end=239
  _globals['_STREAMREQUEST']._serialized_start=40
  _globals['_STREAMREQUEST']._serialized_end=70
  _globals['_STREAMRESPONSE']._serialized_start=72
  _globals['_STREAMRESPONSE']._serialized_end=192
  _globals['_STREAMINGSERVICE']._serialized_start=241
  _globals['_STREAMINGSERVICE']._serialized_end=328
# @@protoc_insertion_point(module_scope)
